/*
 * generated by Xtext
 */
package ar.edu.unq;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class AventuraGraficaUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return ar.edu.unq.ui.internal.AventuraGraficaActivator.getInstance().getInjector("ar.edu.unq.AventuraGrafica");
	}
	
}
