/*
 * generated by Xtext
 */
package ar.edu.unq.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AventuraGraficaUiModule extends ar.edu.unq.ui.AbstractAventuraGraficaUiModule {
	public AventuraGraficaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
