/*
 * generated by Xtext
 */
package ar.edu.unq.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import ar.edu.unq.ui.internal.AventuraGraficaActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AventuraGraficaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AventuraGraficaActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AventuraGraficaActivator.getInstance().getInjector(AventuraGraficaActivator.AR_EDU_UNQ_AVENTURAGRAFICA);
	}
	
}
