/*
 * generated by Xtext
 */
package ar.edu.unq.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractAventuraGraficaValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(ar.edu.unq.aventuraGrafica.AventuraGraficaPackage.eINSTANCE);
		return result;
	}
}
