/**
 * generated by Xtext
 */
package ar.edu.unq.ui.contentassist;

import ar.edu.unq.ui.contentassist.AbstractAventuraGraficaProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class AventuraGraficaProposalProvider extends AbstractAventuraGraficaProposalProvider {
}
