/*
 * generated by Xtext
 */
package ar.edu.unq.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import ar.edu.unq.services.AventuraGraficaGrammarAccess;

public class AventuraGraficaParser extends AbstractContentAssistParser {
	
	@Inject
	private AventuraGraficaGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected ar.edu.unq.ui.contentassist.antlr.internal.InternalAventuraGraficaParser createParser() {
		ar.edu.unq.ui.contentassist.antlr.internal.InternalAventuraGraficaParser result = new ar.edu.unq.ui.contentassist.antlr.internal.InternalAventuraGraficaParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getComandoAccess().getAlternatives(), "rule__Comando__Alternatives");
					put(grammarAccess.getEjecutarAccionAccess().getAlternatives(), "rule__EjecutarAccion__Alternatives");
					put(grammarAccess.getEjecutarAccionAccess().getAlternatives_0_2(), "rule__EjecutarAccion__Alternatives_0_2");
					put(grammarAccess.getAccionAccess().getAlternatives(), "rule__Accion__Alternatives");
					put(grammarAccess.getJuegoAccess().getGroup(), "rule__Juego__Group__0");
					put(grammarAccess.getObjetoAccess().getGroup(), "rule__Objeto__Group__0");
					put(grammarAccess.getObjetoAccess().getGroup_3(), "rule__Objeto__Group_3__0");
					put(grammarAccess.getObjetoAccess().getGroup_4(), "rule__Objeto__Group_4__0");
					put(grammarAccess.getHabitacionAccess().getGroup(), "rule__Habitacion__Group__0");
					put(grammarAccess.getHabitacionAccess().getGroup_7(), "rule__Habitacion__Group_7__0");
					put(grammarAccess.getHabitacionAccess().getGroup_8(), "rule__Habitacion__Group_8__0");
					put(grammarAccess.getHabitacionAccess().getGroup_8_1(), "rule__Habitacion__Group_8_1__0");
					put(grammarAccess.getPosicionAccess().getGroup(), "rule__Posicion__Group__0");
					put(grammarAccess.getMostrarObjetosAccess().getGroup(), "rule__MostrarObjetos__Group__0");
					put(grammarAccess.getDescribirObjetoAccess().getGroup(), "rule__DescribirObjeto__Group__0");
					put(grammarAccess.getRecogerObjetoAccess().getGroup(), "rule__RecogerObjeto__Group__0");
					put(grammarAccess.getMostrarInventarioAccess().getGroup(), "rule__MostrarInventario__Group__0");
					put(grammarAccess.getAccionesAccess().getGroup(), "rule__Acciones__Group__0");
					put(grammarAccess.getEjecutarAccionAccess().getGroup_0(), "rule__EjecutarAccion__Group_0__0");
					put(grammarAccess.getEjecutarAccionAccess().getGroup_1(), "rule__EjecutarAccion__Group_1__0");
					put(grammarAccess.getIrAAccess().getGroup(), "rule__IrA__Group__0");
					put(grammarAccess.getIrAAccess().getGroup_4(), "rule__IrA__Group_4__0");
					put(grammarAccess.getCambiarEstadoAccess().getGroup(), "rule__CambiarEstado__Group__0");
					put(grammarAccess.getEstadoDeObjetoAccess().getGroup(), "rule__EstadoDeObjeto__Group__0");
					put(grammarAccess.getEstadoDeObjetoAccess().getGroup_1(), "rule__EstadoDeObjeto__Group_1__0");
					put(grammarAccess.getJuegoAccess().getObjetosAssignment_0(), "rule__Juego__ObjetosAssignment_0");
					put(grammarAccess.getJuegoAccess().getPosicionAssignment_1(), "rule__Juego__PosicionAssignment_1");
					put(grammarAccess.getJuegoAccess().getHabitacionesAssignment_2(), "rule__Juego__HabitacionesAssignment_2");
					put(grammarAccess.getJuegoAccess().getComandosAssignment_3(), "rule__Juego__ComandosAssignment_3");
					put(grammarAccess.getObjetoAccess().getRecogibleAssignment_1(), "rule__Objeto__RecogibleAssignment_1");
					put(grammarAccess.getObjetoAccess().getNameAssignment_2(), "rule__Objeto__NameAssignment_2");
					put(grammarAccess.getObjetoAccess().getDescripcionAssignment_3_1(), "rule__Objeto__DescripcionAssignment_3_1");
					put(grammarAccess.getObjetoAccess().getEstadoAssignment_4_1(), "rule__Objeto__EstadoAssignment_4_1");
					put(grammarAccess.getObjetoAccess().getAccionesAssignment_5(), "rule__Objeto__AccionesAssignment_5");
					put(grammarAccess.getHabitacionAccess().getFinalAssignment_1(), "rule__Habitacion__FinalAssignment_1");
					put(grammarAccess.getHabitacionAccess().getNameAssignment_2(), "rule__Habitacion__NameAssignment_2");
					put(grammarAccess.getHabitacionAccess().getDescripcionAssignment_6(), "rule__Habitacion__DescripcionAssignment_6");
					put(grammarAccess.getHabitacionAccess().getEstadoACambiarAssignment_7_2(), "rule__Habitacion__EstadoACambiarAssignment_7_2");
					put(grammarAccess.getHabitacionAccess().getObjetoACambiarAssignment_7_4(), "rule__Habitacion__ObjetoACambiarAssignment_7_4");
					put(grammarAccess.getHabitacionAccess().getValorNuevoAssignment_7_6(), "rule__Habitacion__ValorNuevoAssignment_7_6");
					put(grammarAccess.getHabitacionAccess().getObjetosAssignment_8_1_1(), "rule__Habitacion__ObjetosAssignment_8_1_1");
					put(grammarAccess.getPosicionAccess().getHabitacionAssignment_1(), "rule__Posicion__HabitacionAssignment_1");
					put(grammarAccess.getDescribirObjetoAccess().getObjetoAssignment_1(), "rule__DescribirObjeto__ObjetoAssignment_1");
					put(grammarAccess.getRecogerObjetoAccess().getObjetoAssignment_1(), "rule__RecogerObjeto__ObjetoAssignment_1");
					put(grammarAccess.getAccionesAccess().getObjetoAssignment_1(), "rule__Acciones__ObjetoAssignment_1");
					put(grammarAccess.getEjecutarAccionAccess().getAccionAssignment_0_1(), "rule__EjecutarAccion__AccionAssignment_0_1");
					put(grammarAccess.getEjecutarAccionAccess().getObjetoAssignment_0_3(), "rule__EjecutarAccion__ObjetoAssignment_0_3");
					put(grammarAccess.getEjecutarAccionAccess().getAccionAssignment_1_1(), "rule__EjecutarAccion__AccionAssignment_1_1");
					put(grammarAccess.getEjecutarAccionAccess().getObjetoAssignment_1_2(), "rule__EjecutarAccion__ObjetoAssignment_1_2");
					put(grammarAccess.getIrAAccess().getNameAssignment_1(), "rule__IrA__NameAssignment_1");
					put(grammarAccess.getIrAAccess().getHabitacionAssignment_3(), "rule__IrA__HabitacionAssignment_3");
					put(grammarAccess.getIrAAccess().getVariableAssignment_4_1(), "rule__IrA__VariableAssignment_4_1");
					put(grammarAccess.getIrAAccess().getValorAssignment_4_3(), "rule__IrA__ValorAssignment_4_3");
					put(grammarAccess.getCambiarEstadoAccess().getNameAssignment_1(), "rule__CambiarEstado__NameAssignment_1");
					put(grammarAccess.getCambiarEstadoAccess().getVariableACambiarAssignment_3(), "rule__CambiarEstado__VariableACambiarAssignment_3");
					put(grammarAccess.getCambiarEstadoAccess().getValorNuevoAssignment_5(), "rule__CambiarEstado__ValorNuevoAssignment_5");
					put(grammarAccess.getCambiarEstadoAccess().getVariableCondicionAssignment_7(), "rule__CambiarEstado__VariableCondicionAssignment_7");
					put(grammarAccess.getCambiarEstadoAccess().getValorCondicionalAssignment_9(), "rule__CambiarEstado__ValorCondicionalAssignment_9");
					put(grammarAccess.getEstadoDeObjetoAccess().getNameAssignment_0(), "rule__EstadoDeObjeto__NameAssignment_0");
					put(grammarAccess.getEstadoDeObjetoAccess().getValorAssignment_1_1(), "rule__EstadoDeObjeto__ValorAssignment_1_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			ar.edu.unq.ui.contentassist.antlr.internal.InternalAventuraGraficaParser typedParser = (ar.edu.unq.ui.contentassist.antlr.internal.InternalAventuraGraficaParser) parser;
			typedParser.entryRuleJuego();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public AventuraGraficaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AventuraGraficaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
