/*
 * generated by Xtext
 */
package ar.edu.unq;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class AventuraGraficaStandaloneSetup extends AventuraGraficaStandaloneSetupGenerated{

	public static void doSetup() {
		new AventuraGraficaStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

